### ISSUE TITLE
Question about the use of SingleChildScrollView 

### ISSUE THREAD

**Issue by lalabinxi** [pruthvi145/pizza-delivery-app#1]
Hey man, great work. Thanks for sharing. Had a question about SingleChildScrollView. On some smaller screen sizes, the homepage is cutoff at the bottom in such a way that the cart icon isn't visible unless the user scrolls down. However it isn't clear to the user that scrolling down is even an option. So my question is: is there a way to fit the whole page to any screen size without having to scroll down? 
I'm a beginner and been struggling to find an answer to this for several days. Would appreciate your insight.

**Comment by pruthvi145** [comment]
Hi @lalabinxi, yes it is possible to make UI responsive (UI that looks the same on any screen size) using `MediaQuery`. 
To fit the whole UI into one screen, you can use the relative measures from screen size instead of **absolute values** in all the places. It will take some time to figure out exact values and it's just a matter of try and error. 

**For example:** 
let's say I want the height of the PizzaPalate (white portion) to be 70% of screen size, then I will write 
`height: MediaQuery.of(context).size.height * 0.7` instead of `height: 520` [at this line](https://github.com/pruthvi145/pizza-delivery-app/blob/fe61f9fc92957df8a76162c263fc215b38a7f605/lib/widgets/pizza_palate.dart#L22)

(here `MediaQuery.of(context).size.height` is to get the height of the screen)
And you can do the same thing at all places.

However, the purpose of this project was to just explore the interactions and animations in flutter so I didn't bother for responsiveness. 

Hope this might helped you.

**Comment by pruthvi145** [comment]
@lalabinxi Since there is no response, I am closing this issue hoping your query has resolved. feel free to reopen if needed. Thank you.
